package Main;

import java.util.Arrays;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class StationsZones {

	public Map<String, List<Integer>> MapOfLists(){
		Map<String, List<Integer>> mapOfLists = new HashMap<String, List<Integer>>();
		mapOfLists.put("Blackhorse Road", Arrays.asList(3));
		mapOfLists.put("Brixton", Arrays.asList(2));
		mapOfLists.put("Euston", Arrays.asList(1));
		mapOfLists.put("Finsbury Park", Arrays.asList(2));
		mapOfLists.put("Green Park", Arrays.asList(1));
		mapOfLists.put("Highbury & Islington", Arrays.asList(2));
		mapOfLists.put("King's Cross St. Pancras", Arrays.asList(1));
		mapOfLists.put("Oxford Circus", Arrays.asList(1));
		mapOfLists.put("Pimlico", Arrays.asList(1));
		mapOfLists.put("Stockwell", Arrays.asList(2));
		mapOfLists.put("Seven Sisters", Arrays.asList(3));
		mapOfLists.put("Tottenham Hale", Arrays.asList(3));
		mapOfLists.put("Victoria", Arrays.asList(1));
		mapOfLists.put("London Victoria", Arrays.asList(1));
		mapOfLists.put("Vauxhall", Arrays.asList(1, 2));
		mapOfLists.put("Warren Street", Arrays.asList(1));
		mapOfLists.put("Walthamstow Central", Arrays.asList(3));
		mapOfLists.put("Baker Street", Arrays.asList(1));
		mapOfLists.put("Charing Cross", Arrays.asList(1));
		mapOfLists.put("Elephant & Castle", Arrays.asList(1, 2));
		mapOfLists.put("Embankment", Arrays.asList(1));
		mapOfLists.put("Edgware Road (Bakerloo)", Arrays.asList(1));
		mapOfLists.put("Harrow & Wealdstone", Arrays.asList(5));
		mapOfLists.put("Harlesden", Arrays.asList(3));
		mapOfLists.put("Kenton", Arrays.asList(4));
		mapOfLists.put("Kilburn Park", Arrays.asList(2));
		mapOfLists.put("Kensal Green", Arrays.asList(2));
		mapOfLists.put("Lambeth North", Arrays.asList(1));
		mapOfLists.put("Maida Vale", Arrays.asList(2));
		mapOfLists.put("Marylebone", Arrays.asList(1));
		mapOfLists.put("North Wembley", Arrays.asList(4));
		mapOfLists.put("Paddington", Arrays.asList(1));
		mapOfLists.put("Piccadilly Circus", Arrays.asList(1));
		mapOfLists.put("Queen's Park", Arrays.asList(2));
		mapOfLists.put("Regent's Park", Arrays.asList(1));
		mapOfLists.put("Stonebridge Park", Arrays.asList(3));
		mapOfLists.put("South Kenton", Arrays.asList(4));
		mapOfLists.put("Willesden Junction", Arrays.asList(2, 3));
		mapOfLists.put("Warwick Avenue", Arrays.asList(2));
		mapOfLists.put("Waterloo", Arrays.asList(1));
		mapOfLists.put("London Waterloo", Arrays.asList(1));
		mapOfLists.put("Wembley Central", Arrays.asList(4));
		mapOfLists.put("Barkingside", Arrays.asList(4));
		mapOfLists.put("Buckhurst Hill", Arrays.asList(5));
		mapOfLists.put("Bethnal Green", Arrays.asList(2));
		mapOfLists.put("Bond Street", Arrays.asList(1));
		mapOfLists.put("Bank", Arrays.asList(1));
		mapOfLists.put("Chancery Lane", Arrays.asList(1));
		mapOfLists.put("Chigwell", Arrays.asList(4));
		mapOfLists.put("Debden", Arrays.asList(6));
		mapOfLists.put("East Acton", Arrays.asList(2));
		mapOfLists.put("Ealing Broadway", Arrays.asList(3));
		mapOfLists.put("Epping", Arrays.asList(6));
		mapOfLists.put("Fairlop", Arrays.asList(4));
		mapOfLists.put("Greenford", Arrays.asList(4));
		mapOfLists.put("Grange Hill", Arrays.asList(4));
		mapOfLists.put("Gants Hill", Arrays.asList(4));
		mapOfLists.put("Holborn", Arrays.asList(1));
		mapOfLists.put("Hanger Lane", Arrays.asList(3));
		mapOfLists.put("Hainault", Arrays.asList(4));
		mapOfLists.put("Holland Park", Arrays.asList(2));
		mapOfLists.put("Loughton", Arrays.asList(6));
		mapOfLists.put("Lancaster Gate", Arrays.asList(1));
		mapOfLists.put("Liverpool Street", Arrays.asList(1));
		mapOfLists.put("Leyton", Arrays.asList(3));
		mapOfLists.put("Leytonstone", Arrays.asList(3, 4));
		mapOfLists.put("Marble Arch", Arrays.asList(1));
		mapOfLists.put("Mile End", Arrays.asList(2));
		mapOfLists.put("North Acton", Arrays.asList(2, 3));
		mapOfLists.put("Newbury Park", Arrays.asList(4));
		mapOfLists.put("Notting Hill Gate", Arrays.asList(1, 2));
		mapOfLists.put("Northolt", Arrays.asList(5));
		mapOfLists.put("Perivale", Arrays.asList(4));
		mapOfLists.put("Queensway", Arrays.asList(1));
		mapOfLists.put("Redbridge", Arrays.asList(4));
		mapOfLists.put("Ruislip Gardens", Arrays.asList(5));
		mapOfLists.put("Roding Valley", Arrays.asList(4));
		mapOfLists.put("Shepherd's Bush (Central)", Arrays.asList(2));
		mapOfLists.put("Snaresbrook", Arrays.asList(4));
		mapOfLists.put("St. Paul's", Arrays.asList(1));
		mapOfLists.put("South Ruislip", Arrays.asList(5));
		mapOfLists.put("Stratford", Arrays.asList());
		mapOfLists.put("South Woodford", Arrays.asList(4));
		mapOfLists.put("Tottenham Court Road", Arrays.asList(1));
		mapOfLists.put("Theydon Bois", Arrays.asList(6));
		mapOfLists.put("White City", Arrays.asList(2));
		mapOfLists.put("Woodford", Arrays.asList(4));
		mapOfLists.put("West Ruislip", Arrays.asList(6));
		mapOfLists.put("Wanstead", Arrays.asList(4));
		mapOfLists.put("West Acton", Arrays.asList(3));
		mapOfLists.put("Acton Town", Arrays.asList(3));
		mapOfLists.put("Aldgate East", Arrays.asList(1));
		mapOfLists.put("Bromley-by-Bow", Arrays.asList(2, 3));
		mapOfLists.put("Becontree", Arrays.asList(5));
		mapOfLists.put("Blackfriars", Arrays.asList(1));
		mapOfLists.put("Barking", Arrays.asList(4));
		mapOfLists.put("Barons Court", Arrays.asList(2));
		mapOfLists.put("Bow Road", Arrays.asList(2));
		mapOfLists.put("Bayswater", Arrays.asList(1));
		mapOfLists.put("Cannon Street", Arrays.asList(1));
		mapOfLists.put("Chiswick Park", Arrays.asList(3));
		mapOfLists.put("Dagenham East", Arrays.asList(5));
		mapOfLists.put("Dagenham Heathway", Arrays.asList(5));
		mapOfLists.put("Ealing Common", Arrays.asList(3));
		mapOfLists.put("Earl's Court", Arrays.asList(1, 2));
		mapOfLists.put("East Ham", Arrays.asList(3, 4));
		mapOfLists.put("Elm Park", Arrays.asList(6));
		mapOfLists.put("East Putney", Arrays.asList(2, 3));
		mapOfLists.put("Edgware Road (Circle Line)", Arrays.asList(1));
		mapOfLists.put("Fulham Broadway", Arrays.asList(2));
		mapOfLists.put("Gunnersbury", Arrays.asList(3));
		mapOfLists.put("Gloucester Road", Arrays.asList(1));
		mapOfLists.put("Hornchurch", Arrays.asList(6));
		mapOfLists.put("Hammersmith (Dist&Picc Line)", Arrays.asList(2));
		mapOfLists.put("High Street Kensington", Arrays.asList(1));
		mapOfLists.put("Kensington (Olympia)", Arrays.asList(2));
		mapOfLists.put("Kew Gardens", Arrays.asList(3, 4));
		mapOfLists.put("Monument", Arrays.asList(1));
		mapOfLists.put("Mansion House", Arrays.asList(1));
		mapOfLists.put("Plaistow", Arrays.asList(3));
		mapOfLists.put("Parsons Green", Arrays.asList(2));
		mapOfLists.put("Putney Bridge", Arrays.asList(2));
		mapOfLists.put("Richmond", Arrays.asList(4));
		mapOfLists.put("Ravenscourt Park", Arrays.asList(2));
		mapOfLists.put("Stamford Brook", Arrays.asList(2));
		mapOfLists.put("Southfields", Arrays.asList(3));
		mapOfLists.put("Stepney Green", Arrays.asList(2));
		mapOfLists.put("St. James's Park", Arrays.asList(1));
		mapOfLists.put("South Kensington", Arrays.asList(1));
		mapOfLists.put("Sloane Square", Arrays.asList(1));
		mapOfLists.put("Temple", Arrays.asList(1));
		mapOfLists.put("Turnham Green", Arrays.asList(2));
		mapOfLists.put("Tower Hill", Arrays.asList(1));
		mapOfLists.put("Upminster Bridge", Arrays.asList(6));
		mapOfLists.put("Upton Park", Arrays.asList(3));
		mapOfLists.put("Upminster", Arrays.asList(6));
		mapOfLists.put("Upney", Arrays.asList(4));
		mapOfLists.put("West Brompton", Arrays.asList(2));
		mapOfLists.put("West Ham", Arrays.asList());
		mapOfLists.put("Wimbledon", Arrays.asList(3));
		mapOfLists.put("Wimbledon Park", Arrays.asList(3));
		mapOfLists.put("West Kensington", Arrays.asList(2));
		mapOfLists.put("Whitechapel", Arrays.asList(2));
		mapOfLists.put("Westminster", Arrays.asList(1));
		mapOfLists.put("Bermondsey", Arrays.asList(2));
		mapOfLists.put("Canning Town", Arrays.asList());
		mapOfLists.put("Canons Park", Arrays.asList(5));
		mapOfLists.put("Canada Water", Arrays.asList(2));
		mapOfLists.put("Canary Wharf", Arrays.asList(2));
		mapOfLists.put("Dollis Hill", Arrays.asList(3));
		mapOfLists.put("Finchley Road", Arrays.asList(2));
		mapOfLists.put("Kilburn", Arrays.asList(2));
		mapOfLists.put("Kingsbury", Arrays.asList(4));
		mapOfLists.put("London Bridge", Arrays.asList(1));
		mapOfLists.put("Neasden", Arrays.asList(3));
		mapOfLists.put("North Greenwich", Arrays.asList(2, 3));
		mapOfLists.put("Queensbury", Arrays.asList(4));
		mapOfLists.put("St. John's Wood", Arrays.asList(2));
		mapOfLists.put("Stanmore", Arrays.asList(5));
		mapOfLists.put("Swiss Cottage", Arrays.asList(2));
		mapOfLists.put("Southwark", Arrays.asList(1));
		mapOfLists.put("West Hampstead", Arrays.asList(2));
		mapOfLists.put("Willesden Green", Arrays.asList(2, 3));
		mapOfLists.put("Wembley Park", Arrays.asList(4));
		mapOfLists.put("Aldgate", Arrays.asList(1));
		mapOfLists.put("Amersham", Arrays.asList(9));
		mapOfLists.put("Barbican", Arrays.asList(1));
		mapOfLists.put("Chalfont & Latimer", Arrays.asList(8));
		mapOfLists.put("Chesham", Arrays.asList(9));
		mapOfLists.put("Croxley", Arrays.asList(7));
		mapOfLists.put("Chorleywood", Arrays.asList(7));
		mapOfLists.put("Eastcote", Arrays.asList(5));
		mapOfLists.put("Euston Square", Arrays.asList(1));
		mapOfLists.put("Farringdon", Arrays.asList(1));
		mapOfLists.put("Great Portland Street", Arrays.asList(1));
		mapOfLists.put("Hillingdon", Arrays.asList(6));
		mapOfLists.put("Harrow-on-the-Hill", Arrays.asList(5));
		mapOfLists.put("Ickenham", Arrays.asList(6));
		mapOfLists.put("Moorgate", Arrays.asList(1));
		mapOfLists.put("Moor Park", Arrays.asList(6, 7));
		mapOfLists.put("North Harrow", Arrays.asList(5));
		mapOfLists.put("Northwick Park", Arrays.asList(4));
		mapOfLists.put("Northwood", Arrays.asList(6));
		mapOfLists.put("Northwood Hills", Arrays.asList(6));
		mapOfLists.put("Pinner", Arrays.asList(5));
		mapOfLists.put("Preston Road", Arrays.asList(4));
		mapOfLists.put("Rickmansworth", Arrays.asList(7));
		mapOfLists.put("Ruislip Manor", Arrays.asList(6));
		mapOfLists.put("Ruislip", Arrays.asList(6));
		mapOfLists.put("Rayners Lane", Arrays.asList(5));
		mapOfLists.put("Uxbridge", Arrays.asList(6));
		mapOfLists.put("Watford", Arrays.asList(7));
		mapOfLists.put("West Harrow", Arrays.asList(5));
		mapOfLists.put("Archway", Arrays.asList(2, 3));
		mapOfLists.put("Angel", Arrays.asList(1));
		mapOfLists.put("Balham", Arrays.asList(3));
		mapOfLists.put("Borough", Arrays.asList(1));
		mapOfLists.put("Burnt Oak", Arrays.asList(4));
		mapOfLists.put("Brent Cross", Arrays.asList(3));
		mapOfLists.put("Belsize Park", Arrays.asList(2));
		mapOfLists.put("Chalk Farm", Arrays.asList(2));
		mapOfLists.put("Colindale", Arrays.asList(4));
		mapOfLists.put("Clapham Common", Arrays.asList(2));
		mapOfLists.put("Clapham North", Arrays.asList(2));
		mapOfLists.put("Clapham South", Arrays.asList(2, 3));
		mapOfLists.put("Colliers Wood", Arrays.asList(3));
		mapOfLists.put("Camden Town", Arrays.asList(2));
		mapOfLists.put("East Finchley", Arrays.asList(3));
		mapOfLists.put("Edgware", Arrays.asList(5));
		mapOfLists.put("Finchley Central", Arrays.asList(4));
		mapOfLists.put("Goodge Street", Arrays.asList(1));
		mapOfLists.put("Golders Green", Arrays.asList(3));
		mapOfLists.put("High Barnet", Arrays.asList(5));
		mapOfLists.put("Hendon Central", Arrays.asList(3, 4));
		mapOfLists.put("Highgate", Arrays.asList(3));
		mapOfLists.put("Hampstead", Arrays.asList(2, 3));
		mapOfLists.put("Kennington", Arrays.asList(2));
		mapOfLists.put("Kentish Town", Arrays.asList(2));
		mapOfLists.put("Leicester Square", Arrays.asList(1));
		mapOfLists.put("Morden", Arrays.asList(4));
		mapOfLists.put("Mill Hill East", Arrays.asList(4));
		mapOfLists.put("Mornington Crescent", Arrays.asList(2));
		mapOfLists.put("Old Street", Arrays.asList(1));
		mapOfLists.put("Oval", Arrays.asList(2));
		mapOfLists.put("South Wimbledon", Arrays.asList(3, 4));
		mapOfLists.put("Totteridge & Whetstone", Arrays.asList(4));
		mapOfLists.put("Tooting Bec", Arrays.asList(3));
		mapOfLists.put("Tooting Broadway", Arrays.asList(3));
		mapOfLists.put("Tufnell Park", Arrays.asList(2));
		mapOfLists.put("West Finchley", Arrays.asList(4));
		mapOfLists.put("Woodside Park", Arrays.asList(4));
		mapOfLists.put("Alperton", Arrays.asList(4));
		mapOfLists.put("Arnos Grove", Arrays.asList(4));
		mapOfLists.put("Arsenal", Arrays.asList(2));
		mapOfLists.put("Bounds Green", Arrays.asList(3, 4));
		mapOfLists.put("Boston Manor", Arrays.asList(4));
		mapOfLists.put("Caledonian Road", Arrays.asList(2));
		mapOfLists.put("Covent Garden", Arrays.asList(1));
		mapOfLists.put("Cockfosters", Arrays.asList(5));
		mapOfLists.put("Hatton Cross", Arrays.asList(5, 6));
		mapOfLists.put("Hyde Park Corner", Arrays.asList(1));
		mapOfLists.put("Heathrow Terminal 4", Arrays.asList(6));
		mapOfLists.put("Heathrow Terminal 5", Arrays.asList(6));
		mapOfLists.put("Heathrow Terminals 1-2-3 ", Arrays.asList(6));
		mapOfLists.put("Hounslow Central", Arrays.asList(4));
		mapOfLists.put("Hounslow East", Arrays.asList(4));
		mapOfLists.put("Hounslow West", Arrays.asList(5));
		mapOfLists.put("Holloway Road", Arrays.asList(2));
		mapOfLists.put("Knightsbridge", Arrays.asList(1));
		mapOfLists.put("Manor House", Arrays.asList(2, 3));
		mapOfLists.put("North Ealing", Arrays.asList(3));
		mapOfLists.put("Northfields", Arrays.asList(3));
		mapOfLists.put("Oakwood", Arrays.asList(5));
		mapOfLists.put("Osterley", Arrays.asList(4));
		mapOfLists.put("Park Royal", Arrays.asList(3));
		mapOfLists.put("Russell Square", Arrays.asList(1));
		mapOfLists.put("South Ealing", Arrays.asList(3));
		mapOfLists.put("Southgate", Arrays.asList(4));
		mapOfLists.put("South Harrow", Arrays.asList(5));
		mapOfLists.put("Sudbury Hill", Arrays.asList(4));
		mapOfLists.put("Sudbury Town", Arrays.asList(4));
		mapOfLists.put("Turnpike Lane", Arrays.asList(3));
		mapOfLists.put("Wood Green", Arrays.asList(3));
		mapOfLists.put("Goldhawk Road", Arrays.asList(2));
		mapOfLists.put("Hammersmith (H&C Line)", Arrays.asList(2));
		mapOfLists.put("Ladbroke Grove", Arrays.asList(2));
		mapOfLists.put("Latimer Road", Arrays.asList(2));
		mapOfLists.put("Paddington (H&C Line)-Underground", Arrays.asList(1));
		mapOfLists.put("Royal Oak", Arrays.asList(2));
		mapOfLists.put("Shepherd's Bush Market", Arrays.asList(2));
		mapOfLists.put("Wood Lane", Arrays.asList(2));
		mapOfLists.put("Westbourne Park", Arrays.asList(2));
		return mapOfLists;
	}
}
